global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alertmanager@{{ gcp_project_id }}.local'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'webhook'

receivers:
  - name: 'webhook'
    webhook_configs:
      - url: 'http://127.0.0.1:5001/'