---
- name: Deploy Monitoring Stack
  hosts: monitoring
  become: yes
  vars:
    monitoring_dir: /opt/monitoring
    grafana_admin_password: admin123
    gcp_project_id: rizzup-dev
    
  tasks:
    - name: Ensure monitoring directory exists
      file:
        path: "{{ monitoring_dir }}"
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Copy monitoring configurations
      copy:
        src: "{{ item.src }}"
        dest: "{{ monitoring_dir }}/{{ item.dest }}"
        owner: ubuntu
        group: ubuntu
        mode: '0644'
      loop:
        - { src: ../configs/prometheus.yml, dest: prometheus/prometheus.yml }
        - { src: ../configs/loki-config.yml, dest: loki/loki-config.yml }
        - { src: ../configs/promtail-config.yml, dest: promtail/promtail-config.yml }
        - { src: ../configs/otel-collector.yml, dest: otel/otel-collector.yml }
        - { src: ../configs/grafana-datasources.yml, dest: grafana/datasources.yml }
        - { src: ../configs/grafana-dashboards.yml, dest: grafana/dashboards.yml }

    - name: Create Docker Compose file for monitoring stack
      template:
        src: ../configs/docker-compose.yml.j2
        dest: "{{ monitoring_dir }}/docker-compose.yml"
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Start monitoring stack
      docker_compose:
        project_src: "{{ monitoring_dir }}"
        state: present
        pull: yes
      become_user: ubuntu

    - name: Wait for services to be ready
      wait_for:
        port: "{{ item }}"
        delay: 30
        timeout: 300
      loop:
        - 3000  # Grafana
        - 9090  # Prometheus
        - 3100  # Loki
        - 4317  # OpenTelemetry

    - name: Display service URLs
      debug:
        msg:
          - "Grafana: http://{{ ansible_host }}:3000 (admin/{{ grafana_admin_password }})"
          - "Prometheus: http://{{ ansible_host }}:9090"
          - "Loki: http://{{ ansible_host }}:3100"
          - "OpenTelemetry: http://{{ ansible_host }}:4317"