apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: monitoring
  labels:
    app: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
      - name: jaeger
        image: jaegertracing/all-in-one:latest
        ports:
        - containerPort: 16686
        - containerPort: 14250
        - containerPort: 14268
        - containerPort: 6831
        - containerPort: 6832
        - containerPort: 5778
        env:
        - name: COLLECTOR_OTLP_ENABLED
          value: "true"
        - name: COLLECTOR_ZIPKIN_HOST_PORT
          value: "9411"
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: monitoring
  labels:
    app: jaeger
spec:
  ports:
  - port: 16686
    targetPort: 16686
    name: jaeger-ui
  - port: 14250
    targetPort: 14250
    name: jaeger-grpc
  - port: 14268
    targetPort: 14268
    name: jaeger-http
  - port: 6831
    targetPort: 6831
    name: jaeger-thrift-compact
    protocol: UDP
  - port: 6832
    targetPort: 6832
    name: jaeger-thrift-binary
    protocol: UDP
  - port: 5778
    targetPort: 5778
    name: jaeger-config
  selector:
    app: jaeger
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-collector
  namespace: monitoring
  labels:
    app: jaeger
spec:
  ports:
  - port: 14250
    targetPort: 14250
    name: jaeger-grpc
  - port: 14268
    targetPort: 14268
    name: jaeger-http
  selector:
    app: jaeger
  type: ClusterIP